name: t_store
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Utility package
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.2.0+3
  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6



  # State management:
  get: ^4.6.6
  get_storage: ^2.1.1


  # product specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

   uses-material-design: true

   assets:
     - assets/
     - assets/icons/brands/
     - assets/images/onBoardingImages/
     - assets/images/animated/
     - assets/images/categories/
     - assets/logos/
     - assets/images/banners/
     - assets/images/user/



   fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/Poppins-Light.ttf
           weight: 300
         - asset: assets/fonts/Poppins-Regular.ttf
           weight: 400
         - asset: assets/fonts/Poppins-Italic.ttf
           style: italic
         - asset: assets/fonts/Poppins-Medium.ttf
           weight: 500
         - asset: assets/fonts/Poppins-MediumItalic.ttf
           weight: 500
           style: italic
         - asset: assets/fonts/Poppins-Bold.ttf
           weight: 800
  

